stages:
    - test
    - build

variables:
    http_proxy: "$CODE_PROXY"
    HTTP_PROXY: "$CODE_PROXY"
    https_proxy: "$CODE_PROXY"
    HTTPS_PROXY: "$CODE_PROXY"
    no_proxy: "127.0.0.1,localhost,.siemens.de,.siemens.net,.siemens.com,.siemens.io,.siemens.cloud"
    NO_PROXY: "127.0.0.1,localhost,.siemens.de,.siemens.net,.siemens.com,.siemens.io,.siemens.cloud"

build:
    stage: build
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    variables:
        http_proxy: $CODE_PROXY
        https_proxy: $CODE_PROXY
        no_proxy: code.siemens.com,cr.siemens.com
    script:
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
        - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --build-arg http_proxy=$http_proxy --build-arg HTTP_PROXY=$HTTP_PROXY --build-arg https_proxy=$https_proxy --build-arg HTTPS_PROXY=$HTTPS_PROXY --build-arg no_proxy=$no_proxy --build-arg NO_PROXY=$NO_PROXY
    tags:
        - DOCKER
    only:
        - tags

